sudo: required
dist: trusty
language: ruby
before_install: gem install -N bundler -v '~> 1.11'
cache: bundler
rvm:
  - 2.1
  - 2.2
  - 2.3
  - jruby-9.1.5.0
jdk:
  - oraclejdk8
gemfile:
  - Gemfile
  - gemfiles/rack_1.gemfile
matrix:
  exclude:
  - rvm: 2.1
    gemfile: Gemfile
  - rvm: 2.2
    gemfile: Gemfile
env:
  global:
    - TEST_3SCALE_APP_IDS=4d4b20b9 TEST_3SCALE_APP_KEYS=ecce202ecc2eb8dc7a499c34a34d5987
    - secure: VSElS0KvnufcZKStV7kj6xHFEiWvQkpxk1IEuhKq5JqywniN/6ScaNUFxbBKrOUrqhzXIRUCteBP2wvYRjlNhLFZSnYskzh7dLkOp/WV+WK6KjrdflTiF6UTxW4pBSsg6YDJ/wWJlmwsPVty1pRvOE3ru6uco+dTWCCLn4BvWqc=
