language: ruby
cache: bundler
rvm:
- 1.9.3
- 2.0.0
- 2.1.1
- 2.1.2
- jruby
matrix:
  include:
  - rvm: jruby
    env: JRUBY_OPTS="--2.0"
env:
  global:
    - TEST_3SCALE_APP_IDS=4d4b20b9 TEST_3SCALE_APP_KEYS=ecce202ecc2eb8dc7a499c34a34d5987
    - secure: VSElS0KvnufcZKStV7kj6xHFEiWvQkpxk1IEuhKq5JqywniN/6ScaNUFxbBKrOUrqhzXIRUCteBP2wvYRjlNhLFZSnYskzh7dLkOp/WV+WK6KjrdflTiF6UTxW4pBSsg6YDJ/wWJlmwsPVty1pRvOE3ru6uco+dTWCCLn4BvWqc=
